### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by WaveHack** [zorbathut/dec#4]
Yo, just stumbled upon this repo. Looks like a pretty cool project.

You considered pouring this into a NuGet package?

**Comment by zorbathut** [comment]
I have! I'm going to be honest here, the *only* reason it hasn't happened is because my life has been painfully busy.

I was about to say "if you can track down instructions on how to do that in a Github action that would help a lot, I tried and couldn't find it", but then I decided to try again, and, well, I might've just solved it. So . . . lemme see what I can do. :V

**Comment by zorbathut** [comment]
Alright that was a bit more of a pain than I hoped :V but in theory it's done - check out https://www.nuget.org/packages/dec/ and let me know if you run into trouble!
